name: libc-shm-shim
summary: glibs snap shim to redirect used sharem memory into snap permited sub dir
description: |
   glibs snap shim to redirect used sharem memory into snap permited sub dir

confinement: strict
grade: stable
adopt-info: libpthread
architectures:
    - build-on: armhf
    - build-on: arm64
    - build-on: i386
    - build-on: amd64

parts:
    libpthread:
        plugin: nil
        source: https://git.launchpad.net/ubuntu/+source/glibc
        source-tag: ubuntu/xenial-updates
        source-type: git
        build-packages:
            - rdfind
            - symlinks
            - systemtap-sdt-dev
            - libaudit-dev
            - g++-5
            - wget
            - quilt
            - gawk
        override-pull: |
            snapcraftctl pull
            snapcraftctl set-version $(git describe 2>/dev/null | awk -F '/' '{print $3}')
            rm -rf manual
            quilt push -afq --leave-rejects --quiltrc=../../../quiltrc
            sed -i 's|curpass =.*|curpass = "libc"|g' debian/rules
            sed -i 's|build-arch: $(stamp)build_C.UTF-8 |# build-arch: $(stamp)build_C.UTF-8|g' debian/rules
            sed -i 's|$(stamp)build_locales-all|# $(stamp)build_locales-all|g' debian/rules
            git apply ../../../shm-snap.patch
        override-build: |
            sed -i 's|$(CURDIR)/debian/tmp-$(curpass)|'"${PWD}"'|g' debian/rules.d/build.mk
            mkdir -p etc
            cp debian/local/etc/ld.so.conf etc/
            unset LD_LIBRARY_PATH
            DEB_BUILD_PROFILES='stage0' DEB_BUILD_OPTIONS='nocheck parallel=$(nproc)' debian/rules build-arch
            cd build-tree/*-libc
            make install -j$(nproc)
            cd ../../
            find lib -name 'libpthread*.so*' -exec cp --parents \{\} ${SNAPCRAFT_PART_INSTALL} \;
        build-attributes: [ no-system-libraries, ]
