name: libc-shm-shim
summary: glibc snap shim to redirect used sharem memory into snap permited path
description: |
  glibc snap shim to redirect used sharem memory into snap permited path

confinement: strict
grade: stable
adopt-info: glibc

platforms:
  arm64:
  armhf:
  amd64:

base: core24

parts:
  glibc:
    plugin: nil
    source: https://git.launchpad.net/ubuntu/+source/glibc
    source-branch: ubuntu/noble-updates
    source-depth: 10
    source-type: git
    stage-packages:
      - libc6
    override-pull: |
      craftctl default
      quilt push -afq --leave-rejects --quiltrc=${CRAFT_PROJECT_DIR}/quiltrc
      git apply ${CRAFT_PROJECT_DIR}/shm-snap.patch
    override-build: |
      DEB_BUILD_OPTIONS=nocheck debuild --no-lintian -b -uc -us
      version=$(head -n 1  debian/changelog | sed 's/.*(\(.*\)).*/\1/')
      craftctl set version="${version}"
      dpkg -x  ${CRAFT_PART_BUILD}/../libc6_${version}_${CRAFT_ARCH_BUILD_FOR}.deb ${CRAFT_PART_INSTALL}
    build-attributes:
      - no-patchelf
    stage:
      - 'usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libc.so.6'

build-packages:
  - binutils-for-host
  - bison
  - debhelper
  - devscripts
  - gawk
  - gperf
  - g++
  - libaudit-dev
  - libcap-dev
  - libgd-dev
  - libselinux-dev
  - quilt
  - rdfind
  - symlinks
  - systemtap-sdt-dev
  - wget
  - on amd64:
    - g++-multilib
