name: libc-shm-shim
summary: glibc snap shim to redirect used sharem memory into snap permited path
description: |
  glibc snap shim to redirect used sharem memory into snap permited path

confinement: strict
grade: stable
adopt-info: glibc

architectures:
  - build-on: armhf
  - build-on: arm64
  - build-on: amd64

base: core22

parts:
  glibc:
    plugin: nil
    source: https://git.launchpad.net/ubuntu/+source/glibc
    source-branch: ubuntu/jammy-updates
    source-depth: 10
    source-type: git
    stage-packages:
      - libc6
    override-pull: |
      craftctl default
      craftctl set version=$(head -n 1  debian/changelog | sed 's/.*(\(.*\)).*/\1/')
      quilt push -afq --leave-rejects --quiltrc=${CRAFT_PROJECT_DIR}/quiltrc
      git apply ${CRAFT_PROJECT_DIR}/shm-snap.patch
    override-build: |
      DEB_BUILD_OPTIONS=nocheck debuild -b -uc -us
      cp ${CRAFT_PART_BUILD}/debian/tmp-libc/lib/${CRAFT_ARCH_TRIPLET}/libc.so.* \
         ${CRAFT_PART_INSTALL}/lib/${CRAFT_ARCH_TRIPLET}
      strip --strip-all ${CRAFT_PART_INSTALL}/lib/${CRAFT_ARCH_TRIPLET}/libc.so.*
    build-attributes:
      - no-patchelf
    stage:
      - '*/*/libc.so.6'

build-packages:
  - bison
  - debhelper
  - devscripts
  - gawk
  - gperf
  - g++
  - libaudit-dev
  - libcap-dev
  - libgd-dev
  - libselinux-dev
  - quilt
  - rdfind
  - symlinks
  - systemtap-sdt-dev
  - wget
  - on amd64:
    - g++-multilib
